//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ir.sms1000
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSendIn", Namespace="http://tempuri.org/")]
    public partial class DataSendIn : object
    {
        
        private long ClientIDField;
        
        private string ShortCodeField;
        
        private string CellphoneField;
        
        private string MessageField;
        
        private bool FarsiField;
        
        private bool FlashField;
        
        private string UDHField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShortCode
        {
            get
            {
                return this.ShortCodeField;
            }
            set
            {
                this.ShortCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cellphone
        {
            get
            {
                return this.CellphoneField;
            }
            set
            {
                this.CellphoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Farsi
        {
            get
            {
                return this.FarsiField;
            }
            set
            {
                this.FarsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Flash
        {
            get
            {
                return this.FlashField;
            }
            set
            {
                this.FlashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UDH
        {
            get
            {
                return this.UDHField;
            }
            set
            {
                this.UDHField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSendOut", Namespace="http://tempuri.org/")]
    public partial class DataSendOut : object
    {
        
        private long ClientIDField;
        
        private long ServerIDField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ServerID
        {
            get
            {
                return this.ServerIDField;
            }
            set
            {
                this.ServerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageReceive", Namespace="http://tempuri.org/")]
    public partial class MessageReceive : object
    {
        
        private long RowIDField;
        
        private string DateTimeField;
        
        private string SenderField;
        
        private string ReceiverField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RowID
        {
            get
            {
                return this.RowIDField;
            }
            set
            {
                this.RowIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ir.sms1000.smsproSoap")]
    public interface smsproSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.HelloWorldResponse> HelloWorldAsync(ir.sms1000.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Echo", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.EchoResponse> EchoAsync(ir.sms1000.EchoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doSendSMSResponse> doSendSMSAsync(ir.sms1000.doSendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendArraySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doSendArraySMSResponse> doSendArraySMSAsync(ir.sms1000.doSendArraySMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendSMSArrayC", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doSendSMSArrayCResponse> doSendSMSArrayCAsync(ir.sms1000.doSendSMSArrayCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doSendUDH", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doSendUDHResponse> doSendUDHAsync(ir.sms1000.doSendUDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSResponse> doReceiveSMSAsync(ir.sms1000.doReceiveSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSArrayResponse> doReceiveSMSArrayAsync(ir.sms1000.doReceiveSMSArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doReceiveSMSByFlag", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSByFlagResponse> doReceiveSMSByFlagAsync(ir.sms1000.doReceiveSMSByFlagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doCheckClientID", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.doCheckClientIDResponse> doCheckClientIDAsync(ir.sms1000.doCheckClientIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.getDeliveryResponse> getDeliveryAsync(ir.sms1000.getDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDelivery3", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.getDelivery3Response> getDelivery3Async(ir.sms1000.getDelivery3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryOlder", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.getDeliveryOlderResponse> getDeliveryOlderAsync(ir.sms1000.getDeliveryOlderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.getInfoResponse> getInfoAsync(ir.sms1000.getInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ir.sms1000.getInfoXMLResponse> getInfoXMLAsync(ir.sms1000.getInfoXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ir.sms1000.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ir.sms1000.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Echo", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.EchoRequestBody Body;
        
        public EchoRequest()
        {
        }
        
        public EchoRequest(ir.sms1000.EchoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long param3;
        
        public EchoRequestBody()
        {
        }
        
        public EchoRequestBody(string param1, bool param2, long param3)
        {
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.EchoResponseBody Body;
        
        public EchoResponse()
        {
        }
        
        public EchoResponse(ir.sms1000.EchoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EchoResult;
        
        public EchoResponseBody()
        {
        }
        
        public EchoResponseBody(string EchoResult)
        {
            this.EchoResult = EchoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMS", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendSMSRequestBody Body;
        
        public doSendSMSRequest()
        {
        }
        
        public doSendSMSRequest(ir.sms1000.doSendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uCellphones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool uFarsi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool uTopic;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool uFlash;
        
        public doSendSMSRequestBody()
        {
        }
        
        public doSendSMSRequestBody(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphones = uCellphones;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
            this.uTopic = uTopic;
            this.uFlash = uFlash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendSMSResponseBody Body;
        
        public doSendSMSResponse()
        {
        }
        
        public doSendSMSResponse(ir.sms1000.doSendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doSendSMSResult;
        
        public doSendSMSResponseBody()
        {
        }
        
        public doSendSMSResponseBody(string doSendSMSResult)
        {
            this.doSendSMSResult = doSendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendArraySMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendArraySMS", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendArraySMSRequestBody Body;
        
        public doSendArraySMSRequest()
        {
        }
        
        public doSendArraySMSRequest(ir.sms1000.doSendArraySMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendArraySMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ir.sms1000.ArrayOfString uNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ir.sms1000.ArrayOfString uCellphone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ir.sms1000.ArrayOfString uMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ir.sms1000.ArrayOfBoolean uFarsi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ir.sms1000.ArrayOfBoolean uFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ir.sms1000.ArrayOfString uUDH;
        
        public doSendArraySMSRequestBody()
        {
        }
        
        public doSendArraySMSRequestBody(string uUsername, string uPassword, ir.sms1000.ArrayOfString uNumber, ir.sms1000.ArrayOfString uCellphone, ir.sms1000.ArrayOfString uMessage, ir.sms1000.ArrayOfBoolean uFarsi, ir.sms1000.ArrayOfBoolean uFlash, ir.sms1000.ArrayOfString uUDH)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphone = uCellphone;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
            this.uFlash = uFlash;
            this.uUDH = uUDH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendArraySMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendArraySMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendArraySMSResponseBody Body;
        
        public doSendArraySMSResponse()
        {
        }
        
        public doSendArraySMSResponse(ir.sms1000.doSendArraySMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendArraySMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ir.sms1000.ArrayOfString doSendArraySMSResult;
        
        public doSendArraySMSResponseBody()
        {
        }
        
        public doSendArraySMSResponseBody(ir.sms1000.ArrayOfString doSendArraySMSResult)
        {
            this.doSendArraySMSResult = doSendArraySMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSArrayCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSArrayC", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendSMSArrayCRequestBody Body;
        
        public doSendSMSArrayCRequest()
        {
        }
        
        public doSendSMSArrayCRequest(ir.sms1000.doSendSMSArrayCRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendSMSArrayCRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ir.sms1000.DataSendIn[] uDataSendIn;
        
        public doSendSMSArrayCRequestBody()
        {
        }
        
        public doSendSMSArrayCRequestBody(string uUsername, string uPassword, ir.sms1000.DataSendIn[] uDataSendIn)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uDataSendIn = uDataSendIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSArrayCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSArrayCResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendSMSArrayCResponseBody Body;
        
        public doSendSMSArrayCResponse()
        {
        }
        
        public doSendSMSArrayCResponse(ir.sms1000.doSendSMSArrayCResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendSMSArrayCResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ir.sms1000.DataSendOut[] doSendSMSArrayCResult;
        
        public doSendSMSArrayCResponseBody()
        {
        }
        
        public doSendSMSArrayCResponseBody(ir.sms1000.DataSendOut[] doSendSMSArrayCResult)
        {
            this.doSendSMSArrayCResult = doSendSMSArrayCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendUDHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendUDH", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendUDHRequestBody Body;
        
        public doSendUDHRequest()
        {
        }
        
        public doSendUDHRequest(ir.sms1000.doSendUDHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendUDHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uCellphones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uUDH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string uMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool uFarsi;
        
        public doSendUDHRequestBody()
        {
        }
        
        public doSendUDHRequestBody(string uUsername, string uPassword, string uNumber, string uCellphones, string uUDH, string uMessage, bool uFarsi)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphones = uCellphones;
            this.uUDH = uUDH;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendUDHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendUDHResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doSendUDHResponseBody Body;
        
        public doSendUDHResponse()
        {
        }
        
        public doSendUDHResponse(ir.sms1000.doSendUDHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doSendUDHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doSendUDHResult;
        
        public doSendUDHResponseBody()
        {
        }
        
        public doSendUDHResponseBody(string doSendUDHResult)
        {
            this.doSendUDHResult = doSendUDHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMS", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doReceiveSMSRequestBody Body;
        
        public doReceiveSMSRequest()
        {
        }
        
        public doReceiveSMSRequest(ir.sms1000.doReceiveSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSRequestBody()
        {
        }
        
        public doReceiveSMSRequestBody(string uUsername, string uPassword, long uLastRowID)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doReceiveSMSResponseBody Body;
        
        public doReceiveSMSResponse()
        {
        }
        
        public doReceiveSMSResponse(ir.sms1000.doReceiveSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doReceiveSMSResult;
        
        public doReceiveSMSResponseBody()
        {
        }
        
        public doReceiveSMSResponseBody(string doReceiveSMSResult)
        {
            this.doReceiveSMSResult = doReceiveSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSArray", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doReceiveSMSArrayRequestBody Body;
        
        public doReceiveSMSArrayRequest()
        {
        }
        
        public doReceiveSMSArrayRequest(ir.sms1000.doReceiveSMSArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSArrayRequestBody()
        {
        }
        
        public doReceiveSMSArrayRequestBody(string uUsername, string uPassword, long uLastRowID)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSArrayResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doReceiveSMSArrayResponseBody Body;
        
        public doReceiveSMSArrayResponse()
        {
        }
        
        public doReceiveSMSArrayResponse(ir.sms1000.doReceiveSMSArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ir.sms1000.MessageReceive[] doReceiveSMSArrayResult;
        
        public doReceiveSMSArrayResponseBody()
        {
        }
        
        public doReceiveSMSArrayResponseBody(ir.sms1000.MessageReceive[] doReceiveSMSArrayResult)
        {
            this.doReceiveSMSArrayResult = doReceiveSMSArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSByFlagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSByFlag", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doReceiveSMSByFlagRequestBody Body;
        
        public doReceiveSMSByFlagRequest()
        {
        }
        
        public doReceiveSMSByFlagRequest(ir.sms1000.doReceiveSMSByFlagRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSByFlagRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public doReceiveSMSByFlagRequestBody()
        {
        }
        
        public doReceiveSMSByFlagRequestBody(string uUsername, string uPassword)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSByFlagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSByFlagResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doReceiveSMSByFlagResponseBody Body;
        
        public doReceiveSMSByFlagResponse()
        {
        }
        
        public doReceiveSMSByFlagResponse(ir.sms1000.doReceiveSMSByFlagResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doReceiveSMSByFlagResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doReceiveSMSByFlagResult;
        
        public doReceiveSMSByFlagResponseBody()
        {
        }
        
        public doReceiveSMSByFlagResponseBody(string doReceiveSMSByFlagResult)
        {
            this.doReceiveSMSByFlagResult = doReceiveSMSByFlagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCheckClientIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCheckClientID", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doCheckClientIDRequestBody Body;
        
        public doCheckClientIDRequest()
        {
        }
        
        public doCheckClientIDRequest(ir.sms1000.doCheckClientIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doCheckClientIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uClientIDs;
        
        public doCheckClientIDRequestBody()
        {
        }
        
        public doCheckClientIDRequestBody(string uUsername, string uClientIDs)
        {
            this.uUsername = uUsername;
            this.uClientIDs = uClientIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCheckClientIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCheckClientIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.doCheckClientIDResponseBody Body;
        
        public doCheckClientIDResponse()
        {
        }
        
        public doCheckClientIDResponse(ir.sms1000.doCheckClientIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doCheckClientIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doCheckClientIDResult;
        
        public doCheckClientIDResponseBody()
        {
        }
        
        public doCheckClientIDResponseBody(string doCheckClientIDResult)
        {
            this.doCheckClientIDResult = doCheckClientIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDelivery", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getDeliveryRequestBody Body;
        
        public getDeliveryRequest()
        {
        }
        
        public getDeliveryRequest(ir.sms1000.getDeliveryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public getDeliveryRequestBody()
        {
        }
        
        public getDeliveryRequestBody(string uUsername, string uReturnIDs)
        {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getDeliveryResponseBody Body;
        
        public getDeliveryResponse()
        {
        }
        
        public getDeliveryResponse(ir.sms1000.getDeliveryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeliveryResult;
        
        public getDeliveryResponseBody()
        {
        }
        
        public getDeliveryResponseBody(string getDeliveryResult)
        {
            this.getDeliveryResult = getDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDelivery3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDelivery3", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getDelivery3RequestBody Body;
        
        public getDelivery3Request()
        {
        }
        
        public getDelivery3Request(ir.sms1000.getDelivery3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDelivery3RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public getDelivery3RequestBody()
        {
        }
        
        public getDelivery3RequestBody(string uUsername, string uReturnIDs)
        {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDelivery3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDelivery3Response", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getDelivery3ResponseBody Body;
        
        public getDelivery3Response()
        {
        }
        
        public getDelivery3Response(ir.sms1000.getDelivery3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDelivery3ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDelivery3Result;
        
        public getDelivery3ResponseBody()
        {
        }
        
        public getDelivery3ResponseBody(string getDelivery3Result)
        {
            this.getDelivery3Result = getDelivery3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryOlderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryOlder", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getDeliveryOlderRequestBody Body;
        
        public getDeliveryOlderRequest()
        {
        }
        
        public getDeliveryOlderRequest(ir.sms1000.getDeliveryOlderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryOlderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public getDeliveryOlderRequestBody()
        {
        }
        
        public getDeliveryOlderRequestBody(string uUsername, string uReturnIDs)
        {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryOlderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryOlderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getDeliveryOlderResponseBody Body;
        
        public getDeliveryOlderResponse()
        {
        }
        
        public getDeliveryOlderResponse(ir.sms1000.getDeliveryOlderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryOlderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeliveryOlderResult;
        
        public getDeliveryOlderResponseBody()
        {
        }
        
        public getDeliveryOlderResponseBody(string getDeliveryOlderResult)
        {
            this.getDeliveryOlderResult = getDeliveryOlderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfo", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getInfoRequestBody Body;
        
        public getInfoRequest()
        {
        }
        
        public getInfoRequest(ir.sms1000.getInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long uCredit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uExpireDate;
        
        public getInfoRequestBody()
        {
        }
        
        public getInfoRequestBody(string uUsername, string uPassword, long uCredit, string uExpireDate)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uCredit = uCredit;
            this.uExpireDate = uExpireDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getInfoResponseBody Body;
        
        public getInfoResponse()
        {
        }
        
        public getInfoResponse(ir.sms1000.getInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool getInfoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long uCredit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uExpireDate;
        
        public getInfoResponseBody()
        {
        }
        
        public getInfoResponseBody(bool getInfoResult, long uCredit, string uExpireDate)
        {
            this.getInfoResult = getInfoResult;
            this.uCredit = uCredit;
            this.uExpireDate = uExpireDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoXML", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getInfoXMLRequestBody Body;
        
        public getInfoXMLRequest()
        {
        }
        
        public getInfoXMLRequest(ir.sms1000.getInfoXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public getInfoXMLRequestBody()
        {
        }
        
        public getInfoXMLRequestBody(string uUsername, string uPassword)
        {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ir.sms1000.getInfoXMLResponseBody Body;
        
        public getInfoXMLResponse()
        {
        }
        
        public getInfoXMLResponse(ir.sms1000.getInfoXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInfoXMLResult;
        
        public getInfoXMLResponseBody()
        {
        }
        
        public getInfoXMLResponseBody(string getInfoXMLResult)
        {
            this.getInfoXMLResult = getInfoXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface smsproSoapChannel : ir.sms1000.smsproSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class smsproSoapClient : System.ServiceModel.ClientBase<ir.sms1000.smsproSoap>, ir.sms1000.smsproSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public smsproSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(smsproSoapClient.GetBindingForEndpoint(endpointConfiguration), smsproSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsproSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(smsproSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsproSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(smsproSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public smsproSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.HelloWorldResponse> ir.sms1000.smsproSoap.HelloWorldAsync(ir.sms1000.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.HelloWorldResponse> HelloWorldAsync()
        {
            ir.sms1000.HelloWorldRequest inValue = new ir.sms1000.HelloWorldRequest();
            inValue.Body = new ir.sms1000.HelloWorldRequestBody();
            return ((ir.sms1000.smsproSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.EchoResponse> ir.sms1000.smsproSoap.EchoAsync(ir.sms1000.EchoRequest request)
        {
            return base.Channel.EchoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.EchoResponse> EchoAsync(string param1, bool param2, long param3)
        {
            ir.sms1000.EchoRequest inValue = new ir.sms1000.EchoRequest();
            inValue.Body = new ir.sms1000.EchoRequestBody();
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            return ((ir.sms1000.smsproSoap)(this)).EchoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doSendSMSResponse> ir.sms1000.smsproSoap.doSendSMSAsync(ir.sms1000.doSendSMSRequest request)
        {
            return base.Channel.doSendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doSendSMSResponse> doSendSMSAsync(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash)
        {
            ir.sms1000.doSendSMSRequest inValue = new ir.sms1000.doSendSMSRequest();
            inValue.Body = new ir.sms1000.doSendSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            return ((ir.sms1000.smsproSoap)(this)).doSendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doSendArraySMSResponse> ir.sms1000.smsproSoap.doSendArraySMSAsync(ir.sms1000.doSendArraySMSRequest request)
        {
            return base.Channel.doSendArraySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doSendArraySMSResponse> doSendArraySMSAsync(string uUsername, string uPassword, ir.sms1000.ArrayOfString uNumber, ir.sms1000.ArrayOfString uCellphone, ir.sms1000.ArrayOfString uMessage, ir.sms1000.ArrayOfBoolean uFarsi, ir.sms1000.ArrayOfBoolean uFlash, ir.sms1000.ArrayOfString uUDH)
        {
            ir.sms1000.doSendArraySMSRequest inValue = new ir.sms1000.doSendArraySMSRequest();
            inValue.Body = new ir.sms1000.doSendArraySMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphone = uCellphone;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            return ((ir.sms1000.smsproSoap)(this)).doSendArraySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doSendSMSArrayCResponse> ir.sms1000.smsproSoap.doSendSMSArrayCAsync(ir.sms1000.doSendSMSArrayCRequest request)
        {
            return base.Channel.doSendSMSArrayCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doSendSMSArrayCResponse> doSendSMSArrayCAsync(string uUsername, string uPassword, ir.sms1000.DataSendIn[] uDataSendIn)
        {
            ir.sms1000.doSendSMSArrayCRequest inValue = new ir.sms1000.doSendSMSArrayCRequest();
            inValue.Body = new ir.sms1000.doSendSMSArrayCRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uDataSendIn = uDataSendIn;
            return ((ir.sms1000.smsproSoap)(this)).doSendSMSArrayCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doSendUDHResponse> ir.sms1000.smsproSoap.doSendUDHAsync(ir.sms1000.doSendUDHRequest request)
        {
            return base.Channel.doSendUDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doSendUDHResponse> doSendUDHAsync(string uUsername, string uPassword, string uNumber, string uCellphones, string uUDH, string uMessage, bool uFarsi)
        {
            ir.sms1000.doSendUDHRequest inValue = new ir.sms1000.doSendUDHRequest();
            inValue.Body = new ir.sms1000.doSendUDHRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uUDH = uUDH;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            return ((ir.sms1000.smsproSoap)(this)).doSendUDHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSResponse> ir.sms1000.smsproSoap.doReceiveSMSAsync(ir.sms1000.doReceiveSMSRequest request)
        {
            return base.Channel.doReceiveSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSResponse> doReceiveSMSAsync(string uUsername, string uPassword, long uLastRowID)
        {
            ir.sms1000.doReceiveSMSRequest inValue = new ir.sms1000.doReceiveSMSRequest();
            inValue.Body = new ir.sms1000.doReceiveSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            return ((ir.sms1000.smsproSoap)(this)).doReceiveSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSArrayResponse> ir.sms1000.smsproSoap.doReceiveSMSArrayAsync(ir.sms1000.doReceiveSMSArrayRequest request)
        {
            return base.Channel.doReceiveSMSArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSArrayResponse> doReceiveSMSArrayAsync(string uUsername, string uPassword, long uLastRowID)
        {
            ir.sms1000.doReceiveSMSArrayRequest inValue = new ir.sms1000.doReceiveSMSArrayRequest();
            inValue.Body = new ir.sms1000.doReceiveSMSArrayRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            return ((ir.sms1000.smsproSoap)(this)).doReceiveSMSArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSByFlagResponse> ir.sms1000.smsproSoap.doReceiveSMSByFlagAsync(ir.sms1000.doReceiveSMSByFlagRequest request)
        {
            return base.Channel.doReceiveSMSByFlagAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doReceiveSMSByFlagResponse> doReceiveSMSByFlagAsync(string uUsername, string uPassword)
        {
            ir.sms1000.doReceiveSMSByFlagRequest inValue = new ir.sms1000.doReceiveSMSByFlagRequest();
            inValue.Body = new ir.sms1000.doReceiveSMSByFlagRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            return ((ir.sms1000.smsproSoap)(this)).doReceiveSMSByFlagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.doCheckClientIDResponse> ir.sms1000.smsproSoap.doCheckClientIDAsync(ir.sms1000.doCheckClientIDRequest request)
        {
            return base.Channel.doCheckClientIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.doCheckClientIDResponse> doCheckClientIDAsync(string uUsername, string uClientIDs)
        {
            ir.sms1000.doCheckClientIDRequest inValue = new ir.sms1000.doCheckClientIDRequest();
            inValue.Body = new ir.sms1000.doCheckClientIDRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uClientIDs = uClientIDs;
            return ((ir.sms1000.smsproSoap)(this)).doCheckClientIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.getDeliveryResponse> ir.sms1000.smsproSoap.getDeliveryAsync(ir.sms1000.getDeliveryRequest request)
        {
            return base.Channel.getDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.getDeliveryResponse> getDeliveryAsync(string uUsername, string uReturnIDs)
        {
            ir.sms1000.getDeliveryRequest inValue = new ir.sms1000.getDeliveryRequest();
            inValue.Body = new ir.sms1000.getDeliveryRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((ir.sms1000.smsproSoap)(this)).getDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.getDelivery3Response> ir.sms1000.smsproSoap.getDelivery3Async(ir.sms1000.getDelivery3Request request)
        {
            return base.Channel.getDelivery3Async(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.getDelivery3Response> getDelivery3Async(string uUsername, string uReturnIDs)
        {
            ir.sms1000.getDelivery3Request inValue = new ir.sms1000.getDelivery3Request();
            inValue.Body = new ir.sms1000.getDelivery3RequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((ir.sms1000.smsproSoap)(this)).getDelivery3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.getDeliveryOlderResponse> ir.sms1000.smsproSoap.getDeliveryOlderAsync(ir.sms1000.getDeliveryOlderRequest request)
        {
            return base.Channel.getDeliveryOlderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.getDeliveryOlderResponse> getDeliveryOlderAsync(string uUsername, string uReturnIDs)
        {
            ir.sms1000.getDeliveryOlderRequest inValue = new ir.sms1000.getDeliveryOlderRequest();
            inValue.Body = new ir.sms1000.getDeliveryOlderRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((ir.sms1000.smsproSoap)(this)).getDeliveryOlderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.getInfoResponse> ir.sms1000.smsproSoap.getInfoAsync(ir.sms1000.getInfoRequest request)
        {
            return base.Channel.getInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.getInfoResponse> getInfoAsync(string uUsername, string uPassword, long uCredit, string uExpireDate)
        {
            ir.sms1000.getInfoRequest inValue = new ir.sms1000.getInfoRequest();
            inValue.Body = new ir.sms1000.getInfoRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uCredit = uCredit;
            inValue.Body.uExpireDate = uExpireDate;
            return ((ir.sms1000.smsproSoap)(this)).getInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ir.sms1000.getInfoXMLResponse> ir.sms1000.smsproSoap.getInfoXMLAsync(ir.sms1000.getInfoXMLRequest request)
        {
            return base.Channel.getInfoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ir.sms1000.getInfoXMLResponse> getInfoXMLAsync(string uUsername, string uPassword)
        {
            ir.sms1000.getInfoXMLRequest inValue = new ir.sms1000.getInfoXMLRequest();
            inValue.Body = new ir.sms1000.getInfoXMLRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            return ((ir.sms1000.smsproSoap)(this)).getInfoXMLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.smsproSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.smsproSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.smsproSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sms1000.ir/webservice/smspro.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.smsproSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sms1000.ir/webservice/smspro.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            smsproSoap,
            
            smsproSoap12,
        }
    }
}
